# Generated by Django 4.0.2 on 2022-08-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='pub_fechaPublic',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
