# Generated by Django 4.0.2 on 2022-08-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_alter_publicacion_pub_fechapublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='pub_fechaPublic',
            field=models.DateField(auto_now_add=True),
        ),
    ]
