# Generated by Django 4.0.6 on 2022-07-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=10)),
                ('rol_descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
