# Generated by Django 4.0.6 on 2022-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]
    def insert_init_data(apps,schema_editor):
        rol = [{"rol_nombre": "Administracion","rol_descripcion":"Tiene permiso para crear, eliminar, actualizar usuarios y eventos"},{"rol_nombre": "Usuario","rol_descripcion":"Tiene acceso solo de lectura de la informacion y de confirmar eventos"}]
        roles = apps.get_model("Roles","roles")
        for r in rol:
            roles.objects.create(**r)
    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol_descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roles',
            name='rol_nombre',
            field=models.CharField(max_length=255),
        ),
       migrations.RunPython(insert_init_data)
    ]
