# Generated by Django 4.0.2 on 2022-07-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fechaRegistro', models.DateField(auto_now_add=True)),
                ('reg_asistencia', models.BooleanField(default=False)),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventos.eventos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
