# Generated by Django 4.0.2 on 2022-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_asistencia',
            field=models.BooleanField(),
        ),
    ]
